# Generated by Django 5.2.14 on 2026-05-08 14:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_profile_profile_picture'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='profile_picture',
        ),
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='chapters_read_done',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='profile',
            name='chapters_read_goal',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='profile',
            name='problems_solved_done',
            field=models.IntegerField(default=14),
        ),
        migrations.AddField(
            model_name='profile',
            name='problems_solved_goal',
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='sessions_attended_done',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='profile',
            name='sessions_attended_goal',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='profile',
            name='study_hours_done',
            field=models.IntegerField(default=12),
        ),
        migrations.AddField(
            model_name='profile',
            name='study_hours_goal',
            field=models.IntegerField(default=15),
        ),
        migrations.AddField(
            model_name='subject',
            name='icon',
            field=models.CharField(default='code', max_length=50),
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('time', models.TimeField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.subject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
